spring:
  application:
    name: eurekaserver
  security:
    user:
      name: cursoms-eureka-user
      password: ukmeu-orrscsaesr-eu

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
