spring:
  application:
    name: mscartoes
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ukmeu-orrscsaesr-eu@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes


